---
version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven and Docker Engine...
      - apt-get update
      - apt-get install -y software-properties-common
      - add-apt-repository universe
      - apt-get update
      - apt-get install -y maven
      - apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - apt-get update
      - apt-get install -y docker-ce docker-ce-cli containerd.io
  pre_build:
    commands:
      - echo Preparing for build...
      - java -version
      - mvn -version
      - echo "Update Image tag in kubernetes manifest"
      - sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY_URI:latest"'@' deployment.yml
      - echo "Checking AWS CLI Version..."
      - aws --version
  build:
    commands:
      - echo Building the Java application...
      - mvn clean package
      - echo "Generating build artifact..."
      - mkdir -p build-artifacts
      - cp target/*.jar build-artifacts/
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URL:latest .
  post_build:
    commands:
      - set -x
      - echo Running post-build steps...
      - echo "Hsirah@1142" | docker login --username "harish552" --password-stdin
      - echo "Pushing Docker image $REPOSITORY_URL:latest"
      - docker push $REPOSITORY_URL:latest > docker_push.log 2>&1
      - push_result=$?
      - echo "Push result: $push_result"
      - cat docker_push.log
      - if [ $push_result -ne 0 ]; then echo "Docker push failed"; exit 1; fi
      - echo "Pushing completed successfully"
