---
version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven and Docker Engine...
      - apt-get update
      - apt-get install -y software-properties-common
      - add-apt-repository universe
      - apt-get update
      - apt-get install -y maven
      - apt-get install -y apt-transport-https ca-certificates curl gnupg-agent
        software-properties-common
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      - add-apt-repository "deb [arch=amd64]
        https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - apt-get update
      - apt-get install -y docker-ce docker-ce-cli containerd.io
  pre_build:
    commands:
      - echo Preparing for build...
      - java -version
      - mvn -version
      - TAG="$(date +%Y-%m-%d.%H.%M.%S).$(echo
        $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - echo "Update Image tag in kubernetes manifest"
      - sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY_URI:$TAG"'@'
        deployment.yaml
      - echo "Checking AWS CLI Version..."
      - aws --version
  build:
    commands:
      - echo Building the Java application...
      - mvn clean package
      - echo "Generating build artifact..."
      - mkdir -p build-artifacts
      - cp target/*.jar build-artifacts/
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URL:$TAG .
  post_build:
    commands:
      - echo Running post-build steps...
      - aws ssm get-parameters --names "/myapp/docker-credentials/username"
        "/myapp/docker-credentials/passwd" --with-decryption --region us-east-1
        --query 'Parameters[*].{Value:Value}' --        output text >
        docker_creds.txt
      - read -r username password <<< $(cat docker_creds.txt)
      - echo "$password" | docker login --username "$username" --password-stdin
      - docker push $REPOSITORY_URL:$TAG
