---
version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven and Docker Engine...
      - apt-get update
      - apt-get install -y software-properties-common
      - add-apt-repository universe
      - apt-get update
      - apt-get install -y maven
      - apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - apt-get update
      - apt-get install -y docker-ce docker-ce-cli containerd.io
  pre_build:
    commands:
      - echo Preparing for build...
      - java -version
      - mvn -version
  build:
    commands:
      - echo Building the Java application...
      - mvn clean package
      - echo "Generating build artifact..."
      - mkdir -p build-artifacts
      - cp target/*.jar build-artifacts/
      - echo Building Docker image...
      - docker build -t harish552/javaapp_img:latest .
  post_build:
    commands:
      - echo Running post-build steps...
      - docker login --username "harish552" --password-stdin <<< "Hsirah@1142"
        https://docker.io
      - echo pushing docker image to docker hub
      - docker push harish552/javaapp_img:latest
