---
version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing pre-build tools..."
      - apt-get update && apt-get install -y maven
      - java -version
      - mvn -version
  pre_build:
    commands:
      - echo "Compiling the code..."
      - mvn compile
      - echo "Compile complete."
  build:
    commands:
      - echo "Packaging the code..."
      - mvn clean package
      - echo "Package complete."
  artifacts:
  files:
    - '**/*'  # Include all files in the artifact
  discard-paths: yes  # Optional: Remove local paths from artifacts
cache:
  paths:
    - /root/.m2/repository/**/*
      
