---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapplication
  labels:
    app: appjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appjava
  template:
    metadata:
      labels:
        app: appjava
    spec:
      containers:
      - name: game
        image: 
        ports:
        - containerPort: 8082
