---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapplication
  labels:
    app: appjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appjava
  template:
    metadata:
      labels:
        app: appjava
    spec:
      containers:
      - name: game
        image: 961134435444.dkr.ecr.us-east-1.amazonaws.com/my-repo:IMAGE_TAG
        ports:
        - containerPort: 8082